export const GET_MOVIES_REQUESTED = "GET_MOVIES_REQUESTED";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED";

export const GET_MOVIE_REQUESTED = "GET_MOVIE_REQUESTED";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAILED = "GET_MOVIE_FAILED";

export const GET_MORE_MOVIES_REQUESTED = "GET_MORE_MOVIES_REQUESTED";
export const GET_MORE_MOVIES_SUCCESS = "GET_MORE_MOVIES_SUCCESS";
export const GET_MORE_MOVIES_FAILED = "GET_MORE_MOVIES_FAILED";

export const CHANGE_SEARCH_VALUE = "CHANGE_SEARCH_VALUE";
export const CLEAR_MOVIE = "CLEAR_MOVIE";
